"""kip telegram surat xabar id

Revision ID: ce387d077c86
Revises: fe1be70c1f3d
Create Date: 2026-09-10 15:02:02.298604

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce387d077c86'
down_revision: str | None = 'fe1be70c1f3d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiplar', sa.Column('telegram_surat_xabar_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiplar', 'telegram_surat_xabar_id')
    # ### end Alembic commands ###
