"""boshlangich jadvallar

Revision ID: d44858d6182c
Revises: 
Create Date: 2026-08-16 09:41:32.118286

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd44858d6182c'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foydalanuvchilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ism', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('parol_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'operator', 'tayyor_mahsulotlar', name='rol_turi'), nullable=False),
    sa.Column('smena', sa.Enum('A', 'B', 'C', 'D', name='smena_turi'), nullable=True),
    sa.Column('faol', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('xato_urinishlar', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bloklangan_gacha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oxirgi_kirish', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yaratilgan_vaqt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foydalanuvchilar_login'), 'foydalanuvchilar', ['login'], unique=True)
    op.create_table('mahsulotlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod', sa.String(length=20), nullable=False),
    sa.Column('nomi', sa.String(length=50), nullable=False),
    sa.Column('faol', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod')
    )
    op.create_table('sozlamalar',
    sa.Column('kalit', sa.String(length=100), nullable=False),
    sa.Column('qiymat', sa.Text(), nullable=False),
    sa.Column('tavsif', sa.String(length=255), nullable=True),
    sa.Column('yangilangan_vaqt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('kalit')
    )
    op.create_table('stansiyalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomi', sa.String(length=100), nullable=False),
    sa.Column('rs232_port', sa.String(length=20), nullable=False),
    sa.Column('rs232_baudrate', sa.Integer(), nullable=False),
    sa.Column('kamera_manzili', sa.String(length=255), nullable=True),
    sa.Column('faol', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foydalanuvchi_id', sa.Integer(), nullable=False),
    sa.Column('jadval_nomi', sa.String(length=50), nullable=False),
    sa.Column('yozuv_id', sa.Integer(), nullable=False),
    sa.Column('amal', sa.Enum('yaratildi', 'tahrirlandi', 'ochirildi', name='audit_amal_turi'), nullable=False),
    sa.Column('eski_qiymat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('yangi_qiymat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sabab', sa.Text(), nullable=False),
    sa.Column('vaqt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['foydalanuvchi_id'], ['foydalanuvchilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partiyalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mahsulot_id', sa.Integer(), nullable=False),
    sa.Column('partiya_raqami', sa.Integer(), nullable=False),
    sa.Column('holati', sa.Enum('ochiq', 'yopiq', 'sotilgan', name='partiya_holati_turi'), nullable=False),
    sa.Column('yaratgan_id', sa.Integer(), nullable=True),
    sa.Column('yopgan_id', sa.Integer(), nullable=True),
    sa.Column('yaratilgan_vaqt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('yopilgan_vaqt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sotuv_sanasi', sa.Date(), nullable=True),
    sa.Column('xaridor', sa.String(length=200), nullable=True),
    sa.Column('dogovor_raqami', sa.String(length=100), nullable=True),
    sa.Column('sort', sa.String(length=50), nullable=True),
    sa.Column('urama_bilan_vazn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('urama_vazni', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sof_vazn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kondicion_vazni', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sotuv_narxi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('nakladnoy_raqami', sa.String(length=50), nullable=True),
    sa.Column('nakladnoy_pdf_yoli', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['mahsulot_id'], ['mahsulotlar.id'], ),
    sa.ForeignKeyConstraint(['yaratgan_id'], ['foydalanuvchilar.id'], ),
    sa.ForeignKeyConstraint(['yopgan_id'], ['foydalanuvchilar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mahsulot_id', 'partiya_raqami', name='uq_partiya_mahsulot_raqam')
    )
    op.create_table('shubhali_holatlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaqt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('smena', sa.Enum('A', 'B', 'C', 'D', name='smena_turi'), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('stansiya_id', sa.Integer(), nullable=True),
    sa.Column('ogirlik', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('surat_yoli', sa.String(length=500), nullable=True),
    sa.Column('holati', sa.Enum('yangi', 'korib_chiqildi', name='shubhali_holat_statusi_turi'), nullable=False),
    sa.Column('korib_chiqqan_id', sa.Integer(), nullable=True),
    sa.Column('korib_chiqilgan_vaqt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('izoh', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['korib_chiqqan_id'], ['foydalanuvchilar.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['foydalanuvchilar.id'], ),
    sa.ForeignKeyConstraint(['stansiya_id'], ['stansiyalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kiplar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partiya_id', sa.Integer(), nullable=False),
    sa.Column('kip_raqami', sa.Integer(), nullable=False),
    sa.Column('ogirlik', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('smena', sa.Enum('A', 'B', 'C', 'D', name='smena_turi'), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('stansiya_id', sa.Integer(), nullable=True),
    sa.Column('mahalliy_vaqt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vaqt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sinxronlangan', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('surat_yoli', sa.String(length=500), nullable=True),
    sa.Column('holati', sa.Enum('aktiv', 'bekor_qilingan', 'tahrirlangan', name='kip_holati_turi'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['foydalanuvchilar.id'], ),
    sa.ForeignKeyConstraint(['partiya_id'], ['partiyalar.id'], ),
    sa.ForeignKeyConstraint(['stansiya_id'], ['stansiyalar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partiya_id', 'kip_raqami', name='uq_kip_partiya_raqam')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kiplar')
    op.drop_table('shubhali_holatlar')
    op.drop_table('partiyalar')
    op.drop_table('audit_log')
    op.drop_table('stansiyalar')
    op.drop_table('sozlamalar')
    op.drop_table('mahsulotlar')
    op.drop_index(op.f('ix_foydalanuvchilar_login'), table_name='foydalanuvchilar')
    op.drop_table('foydalanuvchilar')
    # ### end Alembic commands ###
