"""mijoz id qoshildi

Revision ID: d982006fe43f
Revises: d44858d6182c
Create Date: 2026-08-16 10:42:04.222819

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd982006fe43f'
down_revision: str | None = 'd44858d6182c'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiplar', sa.Column('mijoz_id', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'kiplar', ['mijoz_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kiplar', type_='unique')
    op.drop_column('kiplar', 'mijoz_id')
    # ### end Alembic commands ###
